export const ROUTES = {
  HOME: "/",
  PRODUCTS: "/products",
  CART: "/cart",
  CHECKOUT: "/checkout",
  CONTACT: "/contact",
  ABOUT: "/about",
  WISHLIST: "/wishlist",
  PROFILE: "/profile",
  MY_ORDERS: "/my-orders",

  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",

  ADMIN: "/admin",
  ADMIN_BRANDS: "/admin/brands",
  ADMIN_CATEGORIES: "/admin/categories",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_ORDERS: "/admin/orders",
  ADMIN_CUSTOMERS: "/admin/customers",
  ADMIN_INVENTORY: "/admin/inventory",
  ADMIN_SETTINGS: "/admin/settings",
  ADMIN_REVIEWS: "/admin/reviews",
  ADMIN_COUPONS: "/admin/coupons",
  ADMIN_MARKETING: "/admin/marketing",
  ADMIN_REPORTS: "/admin/reports",
};
